const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2022.10 - 2022.12",
    title: "Web Development",
    desc: "Le Wagon Tokyo",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2017 - 2018",
    title: "Business Administration Dept.",
    desc: "Soochow University/Master degree",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2013 - 2017",
    title: "Business Administration Dept.",
    desc: "Soochow University/Bachelor degree",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "2021.09 - 2022.09",
    title: "Li & Fung Limited l Taipei, Taiwan",
    posit: "Merchandiser (Pre-order Dept.)",
    desc: "🔹Communicate and follow up with internal and external constituents, including clients, vendors, mills, and colleagues, to solve problems as soon as possible.",
    more: "🔹Build and maintain close relationships with buyers in order to understand their goals and provide them with suitable sourcing services.",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "2021.04 - 2021.09",
    title: "KindMinds Innovations l Taipei, Taiwan",
    posit: "Logistic Assistant",
    desc: "🔹Create sea or express shipment to send products oversea.",
    more: "🔹Tracking packages if arrive on time and calculating the accounts receivable.",
    third: "🔹Weekly checking the Amazon FBA system, sometime the system will have an error.",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "2018.10 - 2020-06",
    title: "Li & Fung Limited l Taipei, Taiwan",
    posit: "Assistant Merchandiser (Production Dept.)",
    desc: "🔹Manage production for the children's accessories / active apparel industry, like monitoring the transit calendars, orders, production progress, and shipping to ensure deliveries.",
    more: "🔹System information update.",
  },
];

export default Data
